# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1168, 876)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setDocumentMode(False)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        MainWindow.setDockNestingEnabled(True)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(245, 0))
        self.tabWidget.setMaximumSize(QtCore.QSize(967, 16777215))
        self.tabWidget.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(10, 0, 221, 91))
        self.groupBox.setObjectName("groupBox")
        self.radioButtonXY = QtWidgets.QRadioButton(self.groupBox)
        self.radioButtonXY.setGeometry(QtCore.QRect(10, 20, 100, 20))
        self.radioButtonXY.setChecked(True)
        self.radioButtonXY.setObjectName("radioButtonXY")
        self.radioButtonXZ = QtWidgets.QRadioButton(self.groupBox)
        self.radioButtonXZ.setGeometry(QtCore.QRect(10, 40, 100, 20))
        self.radioButtonXZ.setObjectName("radioButtonXZ")
        self.radioButtonYZ = QtWidgets.QRadioButton(self.groupBox)
        self.radioButtonYZ.setGeometry(QtCore.QRect(10, 60, 100, 20))
        self.radioButtonYZ.setObjectName("radioButtonYZ")
        self.checkVisibility = QtWidgets.QCheckBox(self.tab)
        self.checkVisibility.setGeometry(QtCore.QRect(20, 120, 201, 20))
        self.checkVisibility.setChecked(True)
        self.checkVisibility.setObjectName("checkVisibility")
        self.pushButton = QtWidgets.QPushButton(self.tab)
        self.pushButton.setGeometry(QtCore.QRect(20, 180, 191, 41))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.tab)
        self.pushButton_2.setGeometry(QtCore.QRect(20, 301, 191, 41))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.tab)
        self.pushButton_3.setGeometry(QtCore.QRect(20, 260, 191, 41))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.tab)
        self.pushButton_4.setGeometry(QtCore.QRect(20, 341, 191, 41))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.tab)
        self.pushButton_5.setGeometry(QtCore.QRect(20, 220, 191, 41))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.tab)
        self.pushButton_6.setGeometry(QtCore.QRect(20, 381, 191, 41))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.tab)
        self.pushButton_7.setGeometry(QtCore.QRect(20, 460, 191, 41))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.tab)
        self.pushButton_8.setGeometry(QtCore.QRect(20, 500, 191, 41))
        self.pushButton_8.setObjectName("pushButton_8")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(30, 430, 101, 16))
        self.label.setObjectName("label")
        self.pushButton_9 = QtWidgets.QPushButton(self.tab)
        self.pushButton_9.setGeometry(QtCore.QRect(20, 540, 191, 41))
        self.pushButton_9.setObjectName("pushButton_9")
        self.tabWidget.addTab(self.tab, "")
        self.horizontalLayout_4.addWidget(self.tabWidget)
        self.vtkContext = QVTKWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vtkContext.sizePolicy().hasHeightForWidth())
        self.vtkContext.setSizePolicy(sizePolicy)
        self.vtkContext.setObjectName("vtkContext")
        self.horizontalLayout_4.addWidget(self.vtkContext)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1168, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuElements = QtWidgets.QMenu(self.menubar)
        self.menuElements.setEnabled(True)
        self.menuElements.setObjectName("menuElements")
        self.menuFixed_Point_of_View = QtWidgets.QMenu(self.menuElements)
        self.menuFixed_Point_of_View.setObjectName("menuFixed_Point_of_View")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionShort_Axis = QtWidgets.QAction(MainWindow)
        self.actionShort_Axis.setCheckable(True)
        self.actionShort_Axis.setChecked(True)
        self.actionShort_Axis.setEnabled(True)
        self.actionShort_Axis.setObjectName("actionShort_Axis")
        self.actionVisualize_Axis = QtWidgets.QAction(MainWindow)
        self.actionVisualize_Axis.setCheckable(True)
        self.actionVisualize_Axis.setChecked(False)
        self.actionVisualize_Axis.setObjectName("actionVisualize_Axis")
        self.actionTractography = QtWidgets.QAction(MainWindow)
        self.actionTractography.setCheckable(True)
        self.actionTractography.setChecked(True)
        self.actionTractography.setObjectName("actionTractography")
        self.actionSeedRandom_Mode = QtWidgets.QAction(MainWindow)
        self.actionSeedRandom_Mode.setCheckable(True)
        self.actionSeedRandom_Mode.setChecked(False)
        self.actionSeedRandom_Mode.setObjectName("actionSeedRandom_Mode")
        self.actionInteractive = QtWidgets.QAction(MainWindow)
        self.actionInteractive.setObjectName("actionInteractive")
        self.actionSeedAutomatic_Mode = QtWidgets.QAction(MainWindow)
        self.actionSeedAutomatic_Mode.setCheckable(True)
        self.actionSeedAutomatic_Mode.setChecked(True)
        self.actionSeedAutomatic_Mode.setEnabled(True)
        self.actionSeedAutomatic_Mode.setObjectName("actionSeedAutomatic_Mode")
        self.actionAbout_Skeleton = QtWidgets.QAction(MainWindow)
        self.actionAbout_Skeleton.setObjectName("actionAbout_Skeleton")
        self.actionSave_StreamLines_for_Matlab = QtWidgets.QAction(MainWindow)
        self.actionSave_StreamLines_for_Matlab.setObjectName("actionSave_StreamLines_for_Matlab")
        self.actionClipping_box = QtWidgets.QAction(MainWindow)
        self.actionClipping_box.setCheckable(True)
        self.actionClipping_box.setChecked(False)
        self.actionClipping_box.setObjectName("actionClipping_box")
        self.actionReset_box = QtWidgets.QAction(MainWindow)
        self.actionReset_box.setObjectName("actionReset_box")
        self.actionX_Y = QtWidgets.QAction(MainWindow)
        self.actionX_Y.setCheckable(False)
        self.actionX_Y.setObjectName("actionX_Y")
        self.actionX_Z = QtWidgets.QAction(MainWindow)
        self.actionX_Z.setCheckable(False)
        self.actionX_Z.setObjectName("actionX_Z")
        self.actionY_Z = QtWidgets.QAction(MainWindow)
        self.actionY_Z.setObjectName("actionY_Z")
        self.actionSeeding_Box = QtWidgets.QAction(MainWindow)
        self.actionSeeding_Box.setCheckable(True)
        self.actionSeeding_Box.setObjectName("actionSeeding_Box")
        self.actionSave_StreamLines_for_VTK = QtWidgets.QAction(MainWindow)
        self.actionSave_StreamLines_for_VTK.setObjectName("actionSave_StreamLines_for_VTK")
        self.actionTake_snapshot = QtWidgets.QAction(MainWindow)
        self.actionTake_snapshot.setObjectName("actionTake_snapshot")
        self.actionVisibility = QtWidgets.QAction(MainWindow)
        self.actionVisibility.setCheckable(True)
        self.actionVisibility.setChecked(True)
        self.actionVisibility.setObjectName("actionVisibility")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionExit)
        self.menuFixed_Point_of_View.addAction(self.actionX_Y)
        self.menuFixed_Point_of_View.addAction(self.actionX_Z)
        self.menuFixed_Point_of_View.addAction(self.actionY_Z)
        self.menuElements.addAction(self.actionVisibility)
        self.menuElements.addAction(self.actionVisualize_Axis)
        self.menuElements.addAction(self.menuFixed_Point_of_View.menuAction())
        self.menuElements.addAction(self.actionTake_snapshot)
        self.menuHelp.addAction(self.actionAbout_Skeleton)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuElements.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.actionOpen.triggered.connect(MainWindow.FileOpen)
        self.actionExit.triggered.connect(MainWindow.FileExit)
        self.actionX_Y.triggered.connect(MainWindow.SetViewXY)
        self.actionX_Z.triggered.connect(MainWindow.SetViewXZ)
        self.actionY_Z.triggered.connect(MainWindow.SetViewYZ)
        self.pushButton.clicked.connect(MainWindow.changePath)
        self.pushButton_3.clicked.connect(MainWindow.restart_total)
        self.pushButton_5.clicked.connect(MainWindow.changePath2)
        self.pushButton_2.clicked.connect(MainWindow.load_grid)
        self.pushButton_4.clicked.connect(MainWindow.save_grid)
        self.pushButton_6.clicked.connect(MainWindow.load_obj)
        self.pushButton_7.clicked.connect(MainWindow.restart)
        self.pushButton_8.clicked.connect(MainWindow.show_last_action)
        self.pushButton_9.clicked.connect(MainWindow.show_next_action)
        self.actionTake_snapshot.triggered.connect(MainWindow.Snapshot)
        self.actionVisualize_Axis.toggled['bool'].connect(MainWindow.ToggleVisualizeAxis)
        self.radioButtonXY.released.connect(MainWindow.SetViewXY)
        self.radioButtonXZ.released.connect(MainWindow.SetViewXZ)
        self.radioButtonYZ.released.connect(MainWindow.SetViewYZ)
        self.checkVisibility.toggled['bool'].connect(MainWindow.ToggleVisibility)
        self.actionVisibility.toggled['bool'].connect(MainWindow.ToggleVisibility)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Qt VTK FFD"))
        self.groupBox.setTitle(_translate("MainWindow", "Point of view"))
        self.radioButtonXY.setText(_translate("MainWindow", "XY plane"))
        self.radioButtonXZ.setText(_translate("MainWindow", "XZ plane"))
        self.radioButtonYZ.setText(_translate("MainWindow", "YZ plane"))
        self.checkVisibility.setText(_translate("MainWindow", "Show scene"))
        self.pushButton.setText(_translate("MainWindow", "choose obj path"))
        self.pushButton_2.setText(_translate("MainWindow", "load FFD"))
        self.pushButton_3.setText(_translate("MainWindow", "reset all"))
        self.pushButton_4.setText(_translate("MainWindow", "save FFD"))
        self.pushButton_5.setText(_translate("MainWindow", "choose FFD path"))
        self.pushButton_6.setText(_translate("MainWindow", "load obj"))
        self.pushButton_7.setText(_translate("MainWindow", "last one"))
        self.pushButton_8.setText(_translate("MainWindow", "next one"))
        self.label.setText(_translate("MainWindow", "For animation:"))
        self.pushButton_9.setText(_translate("MainWindow", "reset"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Visualization"))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Color presets, tuning, scene elements..."))
        self.menuFile.setTitle(_translate("MainWindow", "Fi&le"))
        self.menuElements.setTitle(_translate("MainWindow", "&Visualization"))
        self.menuFixed_Point_of_View.setTitle(_translate("MainWindow", "&Fixed Point of View"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionExit.setText(_translate("MainWindow", "&Exit"))
        self.actionOpen.setText(_translate("MainWindow", "&Open"))
        self.actionShort_Axis.setText(_translate("MainWindow", "&Short Axis"))
        self.actionShort_Axis.setShortcut(_translate("MainWindow", "Ctrl+K"))
        self.actionVisualize_Axis.setText(_translate("MainWindow", "&Visualize Axis"))
        self.actionVisualize_Axis.setShortcut(_translate("MainWindow", "Ctrl+L"))
        self.actionTractography.setText(_translate("MainWindow", "&Tractography"))
        self.actionTractography.setShortcut(_translate("MainWindow", "Ctrl+J"))
        self.actionSeedRandom_Mode.setText(_translate("MainWindow", "&Random"))
        self.actionSeedRandom_Mode.setShortcut(_translate("MainWindow", "Ctrl+I"))
        self.actionInteractive.setText(_translate("MainWindow", "Toggle interaction mode"))
        self.actionInteractive.setShortcut(_translate("MainWindow", "Ctrl+I"))
        self.actionSeedAutomatic_Mode.setText(_translate("MainWindow", "&Automatic"))
        self.actionSeedAutomatic_Mode.setShortcut(_translate("MainWindow", "Ctrl+A"))
        self.actionAbout_Skeleton.setText(_translate("MainWindow", "&About Qt+VTK Skeleton"))
        self.actionSave_StreamLines_for_Matlab.setText(_translate("MainWindow", "&Save StreamLines for MATLAB"))
        self.actionClipping_box.setText(_translate("MainWindow", "&Clipping box"))
        self.actionReset_box.setText(_translate("MainWindow", "&Reset box"))
        self.actionX_Y.setText(_translate("MainWindow", "&X-Y"))
        self.actionX_Z.setText(_translate("MainWindow", "X-&Z"))
        self.actionY_Z.setText(_translate("MainWindow", "&Y-Z"))
        self.actionSeeding_Box.setText(_translate("MainWindow", "&Seeding Box"))
        self.actionSave_StreamLines_for_VTK.setText(_translate("MainWindow", "Save StreamLines for VTK"))
        self.actionTake_snapshot.setText(_translate("MainWindow", "Take snapshot"))
        self.actionVisibility.setText(_translate("MainWindow", "Show scene"))

from qvtkwidget import QVTKWidget
